# docker-compose.yml
version: "3.8"

services:
  android-build:
    image: kotlin-android-ci:latest
    container_name: android-build
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - gradle-cache:/home/gradle/.gradle
    command: bash -c "./gradlew clean assembleDebug"
    # If you want interactive use:
    # entrypoint: ["bash"]

volumes:
  gradle-cache:
